declare @json nvarchar(max)
set @json=N'{
      "customer":[
         {
            "firstName":"Ananthi",
            "lastName":"Velumani",
            "phonenumber":"9876543210",
            "address":"1/172,sathy",
            "city":"Erode",
            "product":[
               {
                  "object":"Pencil",
                  "quantity":"2",
                  "rate":"1",
                  "pricevalue":"2",
                  "purchasedate":"2021-06-20"
               },
			    {
                  "object":"Eraser",
                  "quantity":"2",
                  "rate":"1",
                  "pricevalue":"2",
                  "purchasedate":"2021-06-20"
               }
            ]
         },
         {
            "firstName":"Madhana",
            "lastName":"Ilango",
            "phonenumber":"9876543211",
            "address":"72,sathy",
            "city":"Erode",
            "product":[
               {
                  "object":"Pencil",
                  "quantity":"2",
                  "rate":"1",
                  "pricevalue":"2",
                  "purchasedate":"2021-06-20"
               },
                {
                  "object":"Pen",
                  "quantity":"2",
                  "rate":"1",
                  "pricevalue":"2",
                  "purchasedate":"2021-06-20"
               }
            ]
         },
		 {
            "firstName":"Arvind",
            "lastName":"Chandrasekaran",
            "phonenumber":"9276543212",
            "address":"12,annanagar",
            "city":"Chennai",
            "product":[
               {
                  "object":"Pencil",
                  "quantity":"2",
                  "rate":"1",
                  "pricevalue":"2",
                  "purchasedate":"2021-06-20"
               },
                {
                  "object":"Eraser",
                  "quantity":"2",
                  "rate":"1",
                  "pricevalue":"2",
                  "purchasedate":"2021-06-20"
               }
            ]
         },
		 {
            "firstName":"Sree",
            "lastName":"Parvathi",
            "phonenumber":"9876653210",
            "address":"172,sathya nagar",
            "city":"Erode",
            "product":[
               {
                  "object":"Pencil",
                  "quantity":"2",
                  "rate":"1",
                  "pricevalue":"2",
                  "purchasedate":"2021-06-20"
               },
                {
                  "object":"stapler",
                  "quantity":"2",
                  "rate":"40",
                  "pricevalue":"40",
                  "purchasedate":"2021-06-20"
               }
            ]
         },
		 {
            "firstName":"Ravi",
            "lastName":"Prasath",
            "phonenumber":"9843210789",
            "address":"12,Gandhistreet",
            "city":"Salem",
            "product":[
               {
                  "object":"Pencil",
                  "quantity":"2",
                  "rate":"1",
                  "pricevalue":"2",
                  "purchasedate":"2021-06-20"
               },
                {
                  "object":"Whitener",
                  "quantity":"1",
                  "rate":"15",
                  "pricevalue":"15",
                  "purchasedate":"2021-06-20"
               }
            ]
         },
		 {
            "firstName":"Chandra",
            "lastName":"Lekha",
            "phonenumber":"7896543210",
            "address":"207,KKnagar",
            "city":"Salem",
            "product":[
               {
                  "object":"Pen",
                  "quantity":"2",
                  "rate":"1",
                  "pricevalue":"2",
                  "purchasedate":"2021-06-20"
               },
                {
                  "object":"Pencil-box",
                  "quantity":"2",
                  "rate":"40",
                  "pricevalue":"40",
                  "purchasedate":"2021-06-20"
               }
            ]
         },
		 {
            "firstName":"Chandra",
            "lastName":"Lekha",
            "phonenumber":"7896543210",
            "address":"207,KKnagar",
            "city":"Salem",
            "product":[
               {
                  "object":"Pen",
                  "quantity":"2",
                  "rate":"1",
                  "pricevalue":"2",
                  "purchasedate":"2021-06-20"
               },
                {
                  "object":"Pencil-box",
                  "quantity":"2",
                  "rate":"40",
                  "pricevalue":"40",
                  "purchasedate":"2021-06-20"
               }
            ]
         },
		 
		 {
            "firstName":"Arvind",
            "lastName":"Chandrasekaran",
            "phonenumber":"9276543212",
            "address":"12,annanagar",
            "city":"Chennai",
            "product":[
               {
                  "object":"Pen",
                  "quantity":"2",
                  "rate":"1",
                  "pricevalue":"2",
                  "purchasedate":"2021-06-25"
               },
                {
                  "object":"A4sheet",
                  "quantity":"2",
                  "rate":"4",
                  "pricevalue":"4",
                  "purchasedate":"2021-06-25"
               }
            ]
         }
		  
      ]
}';

exec InsertdataFromjson @json